server:
  port: 80

spring:
  application:
    name: cloud-sentinel-consumer-ribbon-80
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #Nacos服务注册中心地址
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080 #配置Sentinel dashboard地址

management:
  endpoints:
    web:
      exposure:
        include: '*'